CREATE VIEW HimokuView AS
SELECT "HV" AS ViewType, HM.hid AS id,HM.Name AS Name,
	SUM(CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END) AS Total,
	SUM(CASE WHEN HT.mid=1 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Jan,
	SUM(CASE WHEN HT.mid=2 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Feb, 
	SUM(CASE WHEN HT.mid=3 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Mar,
	SUM(CASE WHEN HT.mid=4 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Apr,
	SUM(CASE WHEN HT.mid=5 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS May,
	SUM(CASE WHEN HT.mid=6 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Jun,
	SUM(CASE WHEN HT.mid=7 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Jul,
	SUM(CASE WHEN HT.mid=8 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Aug,
	SUM(CASE WHEN HT.mid=9 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Sep,
	SUM(CASE WHEN HT.mid=10 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Oct,
	SUM(CASE WHEN HT.mid=11 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Nov,
	SUM(CASE WHEN HT.mid=12 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HT.Amount ELSE HT.Amount END ELSE 0 END) AS Dec
FROM HimokuGroupMaster as HGM, HimokuMaster as HM, HimokuTotal AS HT 
ON HGM.hgid=HM.hgid AND HM.hid=HT.hid
GROUP BY HM.hid
ORDER BY HM.hid;
