CREATE VIEW HimokuGroupView AS
SELECT "HGV" AS ViewType, HGM.hgid AS id, HGM.Name AS Name,
	SUM(CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END) AS Total,
	SUM(CASE WHEN HGT.mid=1 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Jan,
	SUM(CASE WHEN HGT.mid=2 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Feb, 
	SUM(CASE WHEN HGT.mid=3 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Mar,
	SUM(CASE WHEN HGT.mid=4 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Apr,
	SUM(CASE WHEN HGT.mid=5 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS May,
	SUM(CASE WHEN HGT.mid=6 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Jun,
	SUM(CASE WHEN HGT.mid=7 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Jul,
	SUM(CASE WHEN HGT.mid=8 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Aug,
	SUM(CASE WHEN HGT.mid=9 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Sep,
	SUM(CASE WHEN HGT.mid=10 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Oct,
	SUM(CASE WHEN HGT.mid=11 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Nov,
	SUM(CASE WHEN HGT.mid=12 THEN CASE WHEN HGM.incomeflg=1 THEN 0-HGT.Amount ELSE HGT.Amount END ELSE 0 END) AS Dec
FROM HimokuGroupMaster as HGM, (SELECT * FROM Kurikoshi UNION SELECT * FROM HimokuGroupTotal) AS HGT 
ON HGM.hgid=HGT.hgid
GROUP BY HGM.hgid
ORDER BY HGM.hgid;
