BEGIN;
CREATE TABLE Tmp (id TEXT PRIMARY KEY,Date TEXT,Desc TEXT, Amount INTEGER,Himoku TEXT);
INSERT INTO Tmp 
SELECT "Z"||Z_PK, replace(substr(ZDATE,1,10),"/","-") AS KDATE,ZTITLE AS DESC,
ZKINGAKU AS AMMOUNT,ZMEMO1 AS Himoku FROM ZANMEMO.ZEVENT;
CREATE INDEX TmpDateIDX ON Tmp(Date);
END;
